### PR TITLE
Refactor the structure of release scripts to facilitate CI management

### PR DESCRIPTION
**Pull request by timmyyuan**
### Motivation

In order to facilitate the management of the release process, we need to strictly standardize the naming of scripts and the structure of related directories 

### Changes

We changed the structure of related scripts and directories.

### Documentation

Not needed

### CODE REVIEW

**Comment by nodece** [comment]
Maybe we can try this: https://goreleaser.com/.

**Comment by timmyyuan** [comment]
@nodece It looks like a good tool, I think we can try it in build.sh later

**Review by zymap — APPROVED** [review]

**Comment by zymap** [comment]
@timmyyuan Do you need to cherry-pick this PR to other branches?

**Comment by timmyyuan** [comment]
Yes, we need to pick it to branch-2.7.x and branch-2.8.x

**Pull request merged**
