### PR TITLE
Support validate token command

### PR DESCRIPTION
**Pull request by zymap**
---
This pull request is base on #150. Please merge #150 at first.

*Motivation*

Support validate token command.

*Modifications*

- Add command `validate`
- Add test for the command

*Command output*

```
USED FOR:
    This command is used for validating a token.

REQUIRED PERMISSION:
    This command does not need any permission.

OUTPUT:
    #The token is valid.
    The subject is (subject), and the expire time is (time).

    #Both the token string and the token file are not specified.
    [✖]  both the token string and the token file are not specified

    #Both the token string and the token file are specified.
    [✖]  both the token string and token file are specified

    #There is no key to validate the token.
    [✖]  none of the validate keys is specified

    #The key used to validate token is specified more than one.
    [✖]  the validate key is specified more than one

Usage: pulsarctl token validate [flags]

Examples:
    #Validate a token string using the specified secret key string.
    pulsarctl token validate --token-string (token) --secret-key-string (secret-key-string)

    #Validate a token file using the specified secret key file.
    pulsarctl token validate --token-string (token) --secret-key-file (secret-key-file-path)

    #Validate a token string using the specified public key file.
    pulsarctl token validate --token-string (token) --public-key-file (public-key-file-path)

    #Validate a token string using the specified base64 encoded secret key string.
    pulsarctl token validate --token-string (token) --secret-key-string (secret-key-string) --base64

    #Validate a token file that signed with the specified secret key string and the specified signature algorithm.
    pulsarctl toke validate --token-string (token) --secret-key-file (secret-key-file-path) --signature-algorithm (algorithm)



Validate a token flags:
  -a, --signature-algorithm string   The signature algorithm is used for generating the token. Valid options are: 'HS256', 'HS384', 'HS512', 'RS256', 'RS384', 'RS512', 'PS256', 'PS384', 'PS512', 'ES256', 'ES384', 'ES512'. (default "RS256")
      --token-string string          The token string that will be validated.
      --token-file string            The token file that will be validated.
      --secret-key-string string     The secret key string that used to validate a token.
      --secret-key-file string       The secret key file that used to validate a token.
      --public-key-file string       The public key file that used to validate a token.
      --base64                       The secret key is base64 encoded or not.
```

### CODE REVIEW

**Comment by sijie** [comment]
please rebase this pull request

**Comment by zymap** [comment]
Because this pull request is base on the #150, I will rebase this pull request after the #150 merged.

**Comment by sijie** [comment]
#150 is merged. Please rebase.

**Comment by zymap** [comment]
@sijie Done. PTAL. Thanks.

**Pull request merged**
