### PR TITLE
Updating fields in utils data

### PR DESCRIPTION
**Pull request by milos-matijasevic**
According to the newest pulsar version, in LedgerInfo there isn't a `timestamp` field, instead, there is the `offloaded` field

```
{
    "ledgerId" : 45043,
    "entries" : 53640,
    "size" : 26299313,
    "offloaded" : true
}
```

If anyone finds out more updated fields, feel free to change them and commit.

### CODE REVIEW

**Comment by zymap** [comment]
Hi @milos-matijasevic Thank you for your contribution! 
Currently, the tests are broken and we haven't run the tests to cover the latest version of Pulsar. I am improving the tests so I want to merge this after the test framework is out. That will make us know what's changes we need in Pulsarctl with the latest Pulsar.

**Comment by milos-matijasevic** [comment]
Good job about fixing tests

**Review by zymap — APPROVED** [review]
Overall looks good. Do you think it should add a test for it?

**Comment by milos-matijasevic** [comment]
Well, first thinking about the test for this is some kind of validation, are all fields from struct present when broker responds.
Also, this then can be done for every request that returns some data.

This should be discussed, maybe there is a better way. What do you think?

**Comment by zymap** [comment]
Sounds good. Would you like to add it to this PR?

**Comment by milos-matijasevic** [comment]
Sure, will add it for the internal stats command first. If it suits I can add it to all others.

**Comment by milos-matijasevic** [comment]
Hey @zymap, sorry for the delay, didn't found any package for this purpose (matching struct and JSON by their keys), so i started implementing one.
That should be finished soon and maybe it is better to do it in a separate pull request, what do you think?

**Comment by zymap** [comment]
Okay. I will merge this PR.

**Pull request merged**
