### PR TITLE
Support show a token content

### PR DESCRIPTION
**Pull request by zymap**
---
This pull request is base on the #151. 

*Motivation*

Support command `show` to show a token algorithm and subject.

*Modifications*

- Add command `show`
- Add test for the command

*Command output*

```
USED FOR:
    This command is used for showing the content of a token.

REQUIRED PERMISSION:
    This command does not need any permission.

OUTPUT:
    #Show the content of the given token.
    The algorithm and subject of the token are (signature algorithm), (subject).

    #There is no token to show.
    [✖]  both the token string and the token file are not specified

    #Too many tokens to show.
    [✖]  both the token string and token file are specified

Usage: pulsarctl token show [flags]

Examples:
    #Read a token from env TOKEN.
    pulsarctl token show

    #Read a token from the given string.
    pulsarctl token show --token-string (token)

    #Read a token from a given file.
    pulsarctl token show --token-file (token)



Show token flags:
      --token-string string   The token string you would like to show the content.
      --token-file string     The token file you would like to show the content.
```

### CODE REVIEW

**Comment by sijie** [comment]
please rebase the pull request

**Comment by zymap** [comment]
Because this pull request is base on the #151, I will rebase this pull request after the #151 merged.

**Comment by sijie** [comment]
@zymap please rebase this pull request.

**Comment by zymap** [comment]
@sijie done. PTAL. Thanks.

**Pull request merged**
