### PR TITLE
Add CI for different OS and website check

### PR DESCRIPTION
**Pull request by zymap**
---

*Motivation*

Add CI to check the Pulsarctl can build successfully at different
OS. And add CI to check if the doc can build successfully.

### CODE REVIEW

**Comment by zymap** [comment]
@sijie @wolfstudy PTAL. Thanks.

**Comment by sijie** [comment]
@zymap please check why CI doesn't pass.

**Comment by zymap** [comment]
The CI is not passed because of this: #144. I rebase the master, now it passed. 

@sijie @wolfstudy PTAL. Thanks.

**Comment by zymap** [comment]
@sijie @wolfstudy PTAL. Thanks.

**Pull request merged**
