### PR TITLE
Enable the race detector in the test environment

### PR DESCRIPTION
**Pull request by timmyyuan**
https://go.dev/doc/articles/race_detector

### CODE REVIEW

**Comment by nodece** [comment]
@timmyyuan Please fix the CI.

**Comment by timmyyuan** [comment]
@nodece Does pulsarctl must be built with CGO_ENABLED=0 ?

**Comment by nodece** [comment]
> @nodece Does pulsarctl must be built with CGO_ENABLED=0 ?

No, we also can set the `CGO_ENABLED=1`, but we need to install the GCC in the docker image.

**Comment by nodece** [comment]
The CI has been passed, but we need to add check the `gcc` command in the docker image, if the `gcc` command not found, we need to install the `gcc`.

**Comment by timmyyuan** [comment]
@nodece `go test -race` is only called in the test environment, do we have to check gcc since the CI passed? Do you mean we'd better keep the same CGO_ENABLED value in the test and production environments ?

**Comment by nodece** [comment]
>go test -race is only called in the test environment, do we have to check gcc since the CI passed (which means a C/C++ compiler is obviously available)  
Yes, you are right.

> Do you mean we'd better keep the same CGO_ENABLED value in the test and production environments?
I think everything is OK.

@timmyyuan Currently, we are using the Pulsar image@2.9.x, so this CI has been passed, but the Pulsar image@2.10.x don't include the `gcc`, so we need to install the `gcc` command.

**Review by nodece — APPROVED** [review]

**Pull request merged**
