### PR TITLE
Refactor pulsar pkg for pulsarctl

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>

Split the pulsar directory into the following structure:

```
├── pulsar
│   ├── admin.go
│   ├── broker_stats.go
│   ├── brokers.go
│   ├── cluster.go
│   ├── common //folder
│   ├── functions.go
│   ├── functions_worker.go
│   ├── namespace.go
│   ├── ns_isolation_policy.go
│   ├── resource_quotas.go
│   ├── schema.go
│   ├── sinks.go
│   ├── sources.go
│   ├── subscription.go
│   ├── tenant.go
│   ├── topic.go
│   └── utils //folder
```

### CODE REVIEW

**Comment by wolfstudy** [comment]
@sijie @zymap PTAL

**Comment by sijie** [comment]
@wolfstudy can you rebase this pull request to latest master?

**Comment by candlerb** [comment]
[Advice regarding package names](https://blog.golang.org/package-names):

> **Avoid meaningless package names**. Packages named `util`, `common`, or `misc` provide clients with no sense of what the package contains. This makes it harder for clients to use the package and makes it harder for maintainers to keep the package focused.

ISTM that the better options are:

1. if these are private implementation details for pulsarctl, then either:
    * put them in the pulsar package as non-exported symbols (they are still accessible to other source files in the same package)
    * use an [internal package](https://golang.org/doc/go1.4#internalpackages)
2. if these are intended for external use, then make separate logical packages (e.g. "message", "topic", "schema" etc)

**Comment by sijie** [comment]
@candlerb thank you for your advice. do you want to send out a pull request to propose a change?

**Comment by candlerb** [comment]
Not really :-)  But as I'd just come across that golang advice, I thought I'd mention it here.

**Pull request merged**
