### PR TITLE
[CI] Using Pulsar cluster to test Pulsarctl

### PR DESCRIPTION
**Pull request by zymap**
---

*Motivation*

We need to enhancement the Pulsarctl test using the pulsar cluster.
To test all requests handled correctly by the proxy.

*Modifications*

- Add simple Pulsar cluster environment
- Using Pulsar cluster to run test

### CODE REVIEW

**Comment by zymap** [comment]
Need merge #157

**Comment by sijie** [comment]
@zymap please rebase to master and fix the CI

**Comment by zymap** [comment]
@sijie Sorry for that I did not realize as earlies as possible the test results are different between the standalone and the cluster. So the tests were failed on the cluster. I think we might need to write some tests for the cluster. Or do you have some suggestions?

**Comment by zymap** [comment]
Using the pull request #167 to replace this. Close this pull request.

**Pull request closed without merging**
