### PR TITLE
Remove omitempty from booleans

### PR DESCRIPTION
**Pull request by jaysonsantos**
With omitempty it is impossible to set false on flags and they get removed from the final JSON
Another change option would be making them pointers of boolean but it would break compatibility with current versions

### CODE REVIEW

**Comment by EronWright** [comment]
It is possible to check whether a flag was set.  Would this be a reasonable alternative?  For example:
https://github.com/streamnative/pulsarctl/blob/f9fe4bdf4dc1d5b3f288765460dc55f162cc7c80/pkg/ctl/context/create_context.go#L135-L144

On on the notion of removing `omitempty`, could you show how that would actually help, and shouldn't all the fields be adjusted?

**Comment by jaysonsantos** [comment]
Hey there, what I am saying applies to the terraform provider that uses pulsarctl, not sure if it would make sense to mix the command line tooling in there, wdyt?
One of the examples is: if you create a sink and on SinkConfig you specify CleanupSubscription = false then delete the sink, it will also delete the subscription, I guess the api's default is to set as true and then it deletes the subscription

**Comment by nodece** [comment]
@jaysonsantos Good catch! we shouldn't set the`omitempty` to  `bool` type.

**Review by nodece — APPROVED** [review]

**Comment by nodece** [comment]
@jaysonsantos Do you make pulsar_sink in terrform-provider-pulsar? I'm working on pusarl_sink, if you are working on this, you can track the https://github.com/streamnative/terraform-provider-pulsar/issues/37.

**Comment by jaysonsantos** [comment]
@nodece i have implemented it here https://github.com/Audibene-GMBH/terraform-provider-pulsar but I am still slowly making things upstream, I would send it after I finish with upgrading the sdk to v2

**Review by zymap — APPROVED** [review]

**Pull request merged**
