### PR TITLE
Add context for pulsarctl

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

Master: #119 

- Add context for pulsarctl
  - pulsarctl context set [options]
  - pulsarctl context get 
  - pulsarctl context rename [options]
  - pulsarctl context use [options]
  - pulsarctl context current
  - pulsarctl context delete [options]
- add test case for context
- remove `maligned` from `golangci.yml`
- support as follows:
  - auth info
  - broker service url
  - bookie service url
- add docs
  - how to use context

### CODE REVIEW

**Comment by wolfstudy** [comment]
The `.pulsar/config` content as follows:

```
auth-info:
  test-2:
    locationoforigin: /Users/wolf4j/.pulsar/config
    tls_trust_certs_file_path: ""
    tls_allow_insecure_connection: false
    token: ""
    tokenFile: ""
contexts:
  test-2:
    admin-service-url: http://159.65.9.22:8080
    bookie-service-url: http://localhost:8080
current-context: ""
```

**Comment by EronWright** [comment]
May I suggest we consider the [XDG base directory standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), i.e. `~/.config/pulsar`.  [Here's](https://wiki.archlinux.org/index.php/XDG_Base_Directory) a list of examples.  [Here's](https://github.com/kubernetes/kubernetes/issues/56402) the Kubernetes issue for same.    I'm not too familiar with the pros/cons.

**Comment by wolfstudy** [comment]
> May I suggest we consider the [XDG base directory standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), i.e. `~/.config/pulsar`. [Here's](https://wiki.archlinux.org/index.php/XDG_Base_Directory) a list of examples. [Here's](https://github.com/kubernetes/kubernetes/issues/56402) the Kubernetes issue for same. I'm not too familiar with the pros/cons.

Thanks @EronWright, In fact, I'm not too familiar with the pros/cons, too.😄

Currently, the context use the default path(`$HOME/.pulsar/config`) , maybe we should make this path configurable.

**Comment by EronWright** [comment]
@wolfstudy regarding configurability, the  XDG spec does define some environment variables to override the location of `~/.config`.   I take your comment to mean that the tool would support a `PULSAR_CONFIG_HOME` environment variable.   The ideas are similar.

If you have some time, please investigate a bit further because it would be difficult to change later, and I do see this suggestion made often in CLI projects.

**Comment by wolfstudy** [comment]
> I take your comment to mean that the tool would support a PULSAR_CONFIG_HOME environment variable. The ideas are similar.

Yes, this is my initial thought

> If you have some time, please investigate a bit further because it would be difficult to change later, and I do see this suggestion made often in CLI projects.

Good idea, already used **XDG Base Directory**, the path same as `$HOME/.config/pulsar`.

About this, XDG Base Directory recommends configuring hidden files in the `.config` directory. What I can think of is that this way can avoid a large number of hidden files under `$ HOME`.

**Comment by sijie** [comment]
Agreed with @EronWright. @wolfstudy can you take a look at this comment?

**Comment by wolfstudy** [comment]
> Agreed with @EronWright. @wolfstudy can you take a look at this comment?

Of course, will fix it. thanks @EronWright

**Comment by wolfstudy** [comment]
@sijie @EronWright fixed done, PTAL again, thanks.

**Comment by sijie** [comment]
@wolfstudy can you rebase this pull request to master?

**Pull request merged**
